In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('hospital_readmissions.csv')

In [3]:
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [4]:
df.dtypes#

age                  object
time_in_hospital      int64
n_lab_procedures      int64
n_procedures          int64
n_medications         int64
n_outpatient          int64
n_inpatient           int64
n_emergency           int64
medical_specialty    object
diag_1               object
diag_2               object
diag_3               object
glucose_test         object
A1Ctest              object
change               object
diabetes_med         object
readmitted           object
dtype: object

In [5]:
df.select_dtypes(include=['int64'])

,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency
0,8,72,1,18,2,0,0
1,3,34,2,13,0,0,0
2,5,45,0,18,0,0,0
3,2,36,0,12,1,0,0
4,1,42,0,7,0,0,0
...,...,...,...,...,...,...,...
24995,14,77,1,30,0,0,0
24996,2,66,0,24,0,0,0
24997,5,12,0,6,0,1,0
24998,2,61,3,15,0,0,0
24999,10,37,1,24,0,0,0

In [7]:
df.loc[df['age']=='[70-80)']

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
9,[70-80),8,37,1,18,0,0,0,Family/GeneralPractice,Respiratory,Respiratory,Other,no,no,yes,yes,no
10,[70-80),1,35,0,7,0,0,0,Missing,Injury,Injury,Injury,no,no,yes,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24978,[70-80),4,25,0,10,0,0,0,Missing,Other,Diabetes,Diabetes,no,no,no,yes,no
24979,[70-80),1,66,0,11,0,0,0,Emergency/Trauma,Respiratory,Circulatory,Circulatory,no,normal,no,yes,yes
24989,[70-80),5,48,1,22,0,0,0,Other,Musculoskeletal,Other,Circulatory,no,no,no,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Missing,Other,Other,Other,normal,no,no,no,yes
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes,no